### ISSUE TITLE
Blog tag view missing elements

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/hugo-starter-buttercms#11]
From checklist: 

## Blog Tags View
- [ ] Route is set to /blog/tag/<tag-slug>/
- [x] SEO title reads: "Sample Blog - tag: *tag <tag title>*"
- [x] SEO description reads: "Sample blog powered by ButterCMS, showing tag: <tag title>."
- [x] Placeholder avatar used if no avatar in customer's Butter account.

**Comment by vlnevyhosteny** [comment]
@ViolanteCodes Could you please provide some info about:

> Route is set to /blog/tag//

?

What I can see:
<img width="999" alt="Screenshot 2022-09-12 at 21 19 50" src="https://user-images.githubusercontent.com/15954946/189737763-6fcb6636-0275-407c-99c0-b7542f004f7d.png">

**Comment by ViolanteCodes** [comment]
Sorry - that comment was a mistake, please ignore the route comment and thank you
