### ISSUE TITLE
Issues With Deploy

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/hugo-starter-buttercms#4]
Tried to deploy this to see what would happen (github secret is set in main repo) and i get a failure: https://share.getcloudapp.com/5zuPyEY1 - it looks like it's because the secret isn't set in the copied repo, which makes sense, but having to set the secret up is not intuitive for workflow - eg., you push the button to clone, which creates a copy of our github repo in your repo--it now tries to deploy the app, but it can't, because the secret isn't set--but you can't have set the secret ahead of time, because the repo didn't exist?

I looked a bit into the netlify button as well, and it looks like you can pass an env variable in the deploy button url (which we've done for our other apps) https://docs.netlify.com/site-deploys/create-deploys/#deploy-to-netlify-button <-- Is there a reason we have to set it as a github secret?

**Comment by vlnevyhosteny** [comment]
@ViolanteCodes 

Currently: If you click "Deploy to Netlify" button the repository itself is not being forked (cloned). It is deployed from **this** repository (https://github.com/ButterCMS/hugo-starter-buttercms) to Netlify. So its using content form current repository and no token is needed to run in Netlify. Content from ButterCMS is fetch via Github Action in **this** repository using token with every push into **main**.

I can see two solutions:

1. Convince users to fork repository, add token to the secrets and than click on "Deploy to Netlify" button.
2. Somehow set up fetching content from ButterCMS on Netlify before build and than move token to Netlify settings. Than we can setup "Deploy to Netlify" button to accept token as an input. Not sure if it is possible.

**Comment by vlnevyhosteny** [comment]
There is Github action that fetch ButterCMS content: https://github.com/ButterCMS/hugo-starter-buttercms/blob/main/.github/workflows/buttercms.yml

**Comment by ViolanteCodes** [comment]
Hi @vlnevyhosteny - I'm wondering if maybe there's just a difference in terminology or how we're describing things:

> Currently: If you click "Deploy to Netlify" button the repository itself is not being forked (cloned). It is deployed from **this** repository (https://github.com/ButterCMS/hugo-starter-buttercms) to Netlify. 

As you can see in this video: https://share.getcloudapp.com/6quG200d, when I click the button, it makes a copy of the repo in my github and I can name the repo whatever I want. I named it "video" here, which didn't previously exist in the repo, and netlify created a new github repo called "video" and deployed that in my github.

This is the behavior we want - for obvious reasons, we don't want user deployments of our project to be indefinitely connected to our repo, because if we make a change to our starter, we don't want it to automatically deploy to their starter, as that could break whatever modifications or changes they have made.
