### ISSUE TITLE
More useful terminal token messages

### ISSUE THREAD

**Issue by ViolanteCodes** [ButterCMS/hugo-starter-buttercms#5]
- [x] https://share.getcloudapp.com/NQujZ9Ae < – can the message in terminal when a token is invalid be more meaningful? Something like, "Your ButterCMS token is not valid. Please check your token and try again."

- [x] token: there is no confirmation message when the data fetches successfully for prebuild. Can we get a message like, “Token accepted. Your ButterCMS data has been fetched successfully.” Or something like that?

**Comment by vlnevyhosteny** [comment]
Added message for invalid token. Also added message before fetching start and after. #13
